#+TITLE: uni uni uni blog blog blog
* thoughts on the world and farther
1. Everything is one.
2. Everything is conscious.
 *but how can 2. be? a rock does in all likelihood not know it is a rock, hence it cannot be conscious.*
3. [@3] Consciousness is not self-awareness or knowledge, consciousness is the experience of a self.
the rock is conscious not in knowing or seeing itself as a rock, but it is conscious in experiencing the way it now is a rock, and will not be in the future.
 *but how can 1. and 2. be? clearly, I am not directly united with you in your consciousness. My consciousness differs from yours.*
4. [@4] At any given time, everything is not one.
5. Time mediates consciousness, hence makes me and you not be each other.
6. Love is consciousnesses perceiving the oneness and reaching closer, imitating the universal being-one as much as it can at any given time.
this notion of love does of course not line up with how we colloquially use it and it is far broader. the sea shaping the shore may very well be love.
7. [@7] Love and time necessitate each other. Without time, love cannot reach, without love, time becomes trivial in a never-changing world.
8. Love is nonetheless the beyond in our consciousness, as it makes us grasp both beyond ourselves and beyond time.
