#+TITLE: uni uni uni blog blog blog
* bunny wanted to know what a cohomology ring is
** singular chain complex
$\newcommand\ZZ{\mathbb Z} \newcommand\RR{\mathbb R}$
if we are given a topological space $X$ (you can imagine a subset of $\RR^{n}$), we might want to study its holeyness. this is what the stereotype of topology about and indeed it kind of pays off to keep this going when you study homology.

how do you study holeyness? well, what's a hole to begin with? to topologists, its more or less a circle that cannot be filled up in the space, e.g. that isnt the boundary of a disk lying in the space.

but defining boundary in a way that makes this work is, while possible, a little inconvenient. that's why instead of circles (and spheres, higher analogues) we consider simplices and possible embeddings in $X$:

the /standard \(n\)-simplex/ $\Delta^{n}$ is a subset of $\RR^{n}$ that is defined as the complex hull of the 0-point as well as all the unit vectors $(1,0,\dots,0), \dots, (0,\dots,0,1)$. for $n=0$, this yields a point, for $n=1$ the unit interval, for $n = 2$ a right triangle, for $n=3$ basically a corner of a cube, and so on. note that these are "solid" and not just the boundaries.
we can use other vectors in $\RR^{n}$ instead of the zero and unit vectors too - this just possibly rotates moves and stretches the simplex, such that its not standard. then, its usually denoted by $[v_0,\dots,v_n]$ where the $v$ are the corners. In particular, the standard n-simplex equals $[0, e_1, \dots, e_n]$.

As discussed, every simplex has a /boundary/. by taking a look at the shapes of the standard n-simplices, you can see that their boundary consists of $n+1$ different \(n-1\)-simplices - for example, $[0,e_1]$ has as its boundary the points $[0], [e_1]$, $[0,e_1,e_2,e_3]$ has the triangles $[0,e_1,e_2],[0,e_1,e_3],[0,e_2,e_3],[e_1,e_2,e_3]$. so to acquire all the boundary simplices, we need to leave each of the endpoints out one by one. Hence, there are embeddings $f^i : \Delta^n \to \Delta^{n+1}$ for $0 \le i \le n$ that just map $\Delta^n$ onto the i-th face of $\Delta^{n+1}$ respectively, we call them the /face maps/.

to talk about simplices lying in $X$, we just consider continuous functions $\Delta^n \to X$. note that we pose no injectivity requirements such that the map can map the entire simplex to e.g. a single point. that is why we call it /singular/ homology, as you will see sooner or later.

this yields a reasonable definition, but its unclear how to work with it. in particular, what mathematical object should our hole-analyzing subjects be? by some fairly involved historical considerations, it has turned out that /abelian groups/ or more generally modules over a ring tend to be the easiest framework to analyze holiness in. in particular, they allow us to define a good notion of boundary operator.

how do we turn our set of simplices in $X$ into an abelian group? there is no obvious group structure on $\Delta^n \to X$ (this notation is meant to imply continuity btw), so instead, we just use it as a generating set for a free abelian group - so define the abelian group $S^n(X)$ of /n-chains/ in $X$ as $\langle \Delta^{n} \to X \rangle$. This means that elements of $S^n(X)$ are just linear combinations of simplices with coefficients in $\ZZ$. there is no relations imposed - even if we e.g. reverse an interval, we dont get the same or a negative simplex, its just another basis element. this is usually a huge group given that its basis is uncountable a lot of the time.

from here on, we can define a /boundary operator/ $d^{n} : S^n(X) \to S^{n-1}(X)$ (index often omitted) that turns n-chains into \(n-1\)-chains. this should be a group homomorphism, but since $S^n(X)$ is free, it suffices to specify its actions on \(n\)-chains $\sigma$.
we define
$$d \sigma = \sum_{i=0}^{n} (-1)^i (\sigma \circ f^i).$$
this is well-defined: $d\sigma$ must embed an $n-1$ simplex in $X$. so to do that, we embed that n-1-simplex in our n-simplex instead using all the possible face maps. next we apply the given embdding $\sigma$ on each of the given faces, basically.
for example, if we are given a 1-simplex $p \in S_1(X)$, e.g. a map $[0,1] \to X$, then $dp = p(1) - p(0)$ (since points are 0-simplices).

the sign of $(-1)^i$ has a geometrical meaning (it more or less orients the boundary of the simplex too lazy to explain), but more importantly it yields $d^n \circ d^{n+1} = 0$ (relatively easy but annoying to compute, its due to some equalities of compositions of face maps).

** singular homology!!!!
so now we have a method to associate to each space a sequence with $d \circ d = 0$, (a so called /chain complex/, that is just abelian groups indexed by natural or integer numbers and $d^{n}$ that fulfill the equation)
$$\dots \overset {d^{n+2}} \to S_{n+1}(X) \overset {d^{n+1}} \to S_n(X) \overset {d^{n}} \to \dots \to S_0(X) \to 0 \to \dots$$
 so it may come to no surprise that given a continuous map $f : X \to Y$, we can find maps $S_n(f) : S_n(X) \to S_n(Y)$ such that the arising grid commutes. In general, commuting families of maps $S_n(X) \to S_n(Y)$ are called /chain maps/.

indeed we can go further - if two continuous functions are homotopic, there is also a so called /chain homotopy/ between their induced chain maps, but that will not play a major role here.

now given such a chain complex (without even knowing how $d$ functions), we can take a closer look at the subobjects induced by $d$. indeed, every $d^n$ defines two of these, namely $\ker d^n \subseteq S_n(X)$ and $\operatorname{im} d^n \subseteq S_{n+1} (X)$. we got $\operatorname{im} d^n \subseteq \ker d^{n-1}$, since $d^{n-1} \circ d^n = 0$ (very small exercise).

we usually call $\ker d^n$ the group of \(n\)-cycles - for example, take the circle line $S^1$ and define an element of $S_1(S^1)$ (unfortunate overlap) as $f+g$, where $f$ maps the interval onto one semicircle, while $g$ maps it onto the other starting where $f$ left off (basically like the recycling symbol but with two instead of three maps). then $f(1) = g(0), g(1) = f(0)$ and $d(f+g) = df + dg = f(1) - f(0) + g(1) - g(0) = 0$. hence $f+g$ is a 1-cycle.

we also usually call $\operatorname{im} d^{n+1}$ the group of \(n\)-boundaries because they are, well, boundaries of other larger simplices. $f+g$ is not a boundary since we cannot "fill the circle" without leaving the line. this suggests that the relationship betwen cycles and boundaries defines the holeyness!!!

define the /\(n\)-th singular homology group/ $H_n(X)$ of $X$ as $\ker d^{n-1}/\operatorname{im} d^n$. unlike the groups of chains this is usually fairly manageably sized and yields some interesting results!!!

in a sense it measures how non-exact the chain complex is - it is called exact if $\ker d^{n-1} = \operatorname{im} d^n$ for all $n$, such that the homology groups are all 0.

theres some basic stuff on exact sequences:
if $0 \to A \to B \to 0$ is exact, that means that the $A \to B$ map is an isomorphism.
if $0 \to A \to B \to C \to 0$ is exact, that means the $A \to B$ map is injective, and the $B \to C$ map is surjective having its kernel given by the image of $A \to B$. in particular, $C$ is isomorphic to $B/A$ in that case.
** basic stuff on homology
(not going to ponder on this for too long just a couple examples to see how this works)
- $H_0(X)$ is just a free group generated by the path components of $X$: clearly $\ker d^0$ is the entire group of chains (e.g. points), and the image is generated by all $y-x$ where $x,y$ are connected by a path, hence in the same path component. so for path connected spaces, it equals $\ZZ$.
- homology is homotopy invariant. doesnt matter what that means - the important part: if a space is contractible, its homology is that of the point, e.g. $H_0(X) = \ZZ, H_n(x) = 0$ otherwise. this applies to $\RR^{n}$ as well as filled out disks and so on.
- let $U_1, U_2$ be open subsets of $X$. then there is an exact sequence
  $$\dots \to H_n(U_1 \cap U_2) \to_{x \mapsto (x,-x)} H_n(U_1) \oplus H_n(U_2) \to_{(x,y) \to x+y} \to H_n(U_1 \cup U_2) \to H_{n-1}(U_{1} \cap U_{2}) \to \dots.$$
  this (the so called mayer-vietoris sequence) allows you to compute homology from homologies of an open cover.
  in particular, let $X$ be a \(n\)-sphere and $U_i$ the two hemispheres. then $U_1 \cap U_2$ is a \(n-1\)-sphere and the $U_i$ are contractible so we get something like

  $$\dots \to 0 \to_{x \mapsto (x,-x)} 0 \oplus 0 \to_{(x,y) \to x+y} \to H_n(S^{n}) \to \ZZ \to 0 \to \dots.$$
  This means that $H_n(S^n)$ must be $\ZZ$ and by more computation we can see that for $k \ge 1$, $H_n(S^k)$ is $\ZZ$ if $n=k$ or $n = 0$ (path component!), else 0.
** cohomology???
ok this is low key a little hard to motivate but now we are given our little chain complex
$$\dots \overset {d^{n+2}} \to S_{n+1}(X) \overset {d^{n+1}} \to S_n(X) \overset {d^{n}} \to \dots \to S_0(X) \to 0 \to \dots$$
right... now what if.... we replaced $S_{n}(X)$ by $S^{n}(X) = \operatorname{Hom}(S_n(X), R)$ for some fixed abelian group and in particular commutative ring $R$ right... wouldnt that be crazy?? indeed it would be, and it yields us a new map too: from our existing boundary maps we get new ones $d_n : S^n(X) \to S^{n+1}(X), d_n(f) = f \circ d^{n+1}$ (check that this is well defined!) with $d_{n+1} \circ d_n = 0$ and a so called cochain complex
$$\dots \overset {d^{n+1}} \leftarrow S^{n+1}(X) \overset {d^{n}} \leftarrow S^n(X) \overset {d^{n-1}} \leftarrow \dots \leftarrow S^0(X) \leftarrow 0 \leftarrow \dots$$
now guess what we can do homology on this thing too - indeed we define the /n-th singular cohomology group/ $H^n(X)$ of $X$ as $\ker d^n/\operatorname{im}d^{n-1}$. this is nice and silly and basically just the same thing as you can see, just with a bunch of dual groups tucked on.

surprisingly enough these can be computed from the regular homology groups quite easily in a matter most wonderful, it just requires extra Ext groups which im not willing to go into really.

however theres some extra structure and thats crazy innit. reconsider simplices again - $\Delta^{n+m}$ kind of "contains" $\Delta^n$ via $[0,\dots,e_n]$ and $\Delta^m$ via $[e_n, \dots, e_{n+m}]$, such that there are maps $f : \Delta^n \to \Delta^{n+m}, b \Delta^m \to \Delta^{n+m}$. So if you are given $c \in S^n(X), d \in S^m(X)$ and $x \in S_{m+n}(X)$, you can compose these (/front/ and /back/ maps) with $x$ yielding elements of $S_n(x), S_m(x)$, on which we can apply $c,d$ for elements of $R$ that we can multiply for a new one.
So define a multiplication operator $S^{n}(X) \times S^m(X) \to S^{n+m}(X)$ via
$(c,d) \mapsto (x \mapsto c(f \circ x) \cdot d(g \circ x))$.

Interestingly, this also induces a multiplication operator on the cohomology groups (to show this we need to show it respects inclusion and quotient blablablka it does!!!). this yields the /cohomology ring/ - by taking the direct sum of all the $H^n(X)$, we get an abelian group on which this multiplication (the /cup product/) is actually associative n so on. it is also graded commutative (e.g. $xy = (-1)^n yx$ where the sign depends on the degrees of $x,y$) and a bunch of other nice stuff. isnt that cool.
