* the future of music
i think the main two forces driving developments in music are essentially waves of nostalgia and scenes in which entirely new things emerge. im going to be mostly talking about hip hop and electronic music because thats where i Know stuff i guess
a couple of mostly nostalgia driven things as of recent seem to be driven by the standard 20-25 year cycle, like the y2k jungle and trance revival, bloghouse/00s dance pop (see charlie xcx for example), this is not necessarily bad but its hard to call it the "music of the future" no matter what

then theres stuff that is essentially completely new, though obviously based on things that have existed before. i think in rap music theres a lot of that currently though most of it fairly short lived (because the trend cycles become shorter and shorter), but i would call stuff like pluggnb, jerk and stepteam productions relatively innovative after all and at most slightly based on "nostalgia bait".
on the electronic side there's like, i dont know really! the spread of what is called "raptor house" through more countries in latin america, new waves of brazilian funk intertwining with drift phonk and reaching viral fame (not that i think the latter usually makes for great music, but it was something new for sure), maybe dariacore? and a new wave of high brow techno, dubstep, idm and drum 'n' bass by people like gyrofield, skee mask, aya, tim reaper... but all of that seems to be essentially "done" already and i'm frustrated about my curiosity for what is next.

of course there is some inherent issue here and there is no proper way to figure out what will form into a coherent scene or genre before it has already materialized as such and it seems impossible to come up with something *entirely* new. but yet things i would count as entirely new emerge all the time so this is evidently false.

anyways there's a couple predictions that are easy to make:

i think (mostly hope?) the dek bass soundsysteme scene from rural india will gain a bit of publicity in the west by the way of "outsider labels" like nyege nyege tapes who already popularized stuff like the extreme kinds of funk mandelao or singeli. maybe the same will hold for some scenes even more people are completely unaware of, i hope so at least!

there will be some 2010s nostalgia waves (indeed we are already moving towards them with dariacore brostep vibes, jerk music and frutiger aero aesthetics and so on), difficult to say how that will materialize though. a possibility may be the k-popification of 2010s edm trap that has already been devloping for a while.

the uk rap underground will blow up more than it already has with artists like fakemink, esdeekid, yt, lancey foux rising to the top of what is possible in one-level-below-mainstream hip hop in the uk. rap of this level of popularity might become even noisier in general, they are already working on it by all means possible.

the electroacoustics, idm, synthesis, improvisation avantgarde will keep doing its thing, but about as much if not way more of what is new will come from completely different usually unexpected sources. as it has been for a while now

i think a lot of the few people reading this will not be familiar with most of the stuff mentioned here. a lot of it is googlable but also feel free to ask i just didnt wanna give a billion sources and examples in advance,.,
